var m;m||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer";m.expectedDataFileDownloads||(m.expectedDataFileDownloads=0);m.expectedDataFileDownloads++;
(()=>{var a=typeof ENVIRONMENT_IS_WASM_WORKER!="undefined"&&ENVIRONMENT_IS_WASM_WORKER;if(!(typeof ENVIRONMENT_IS_PTHREAD!="undefined"&&ENVIRONMENT_IS_PTHREAD||a)){var b=globalThis.process&&globalThis.process.versions&&globalThis.process.versions.node&&globalThis.process.type!="renderer";(async function(c){async function d(h,r){if(b){var u=require("fs").readFileSync(h);return(new Uint8Array(u)).buffer}m.dataFileDownloads||(m.dataFileDownloads={});try{var v=await fetch(h)}catch(F){throw Error(`Network Error: ${h}`,
{e:F});}if(!v.ok)throw Error(`${v.status}: ${v.url}`);u=[];r=Number(v.headers.get("Content-Length")||r);var z=0;m.setStatus&&m.setStatus("Downloading data...");for(v=v.body.getReader();;){var C;({done:C,value:I}=await v.read());if(C)break;u.push(I);z+=I.length;m.dataFileDownloads[h]={loaded:z,total:r};var I=C=0;for(var H of Object.values(m.dataFileDownloads))C+=H.loaded,I+=H.total;m.setStatus&&m.setStatus(`Downloading data... (${C}/${I})`)}h=new Uint8Array(u.map(F=>F.length).reduce((F,Z)=>F+Z,0));
H=0;for(let F of u)h.set(F,H),H+=F.length;return h.buffer}async function e(h){h.FS_createPath("/","Editor",!0,!0);h.FS_createPath("/Editor","Fonts",!0,!0);h.FS_createPath("/Editor","Technique",!0,!0);h.FS_createPath("/Editor/Technique","Shapes",!0,!0);h.FS_createPath("/Editor/Technique","Typography",!0,!0);h.FS_createPath("/Editor/Technique","UI",!0,!0);h.FS_createPath("/","World",!0,!0);h.FS_createPath("/World","Data",!0,!0);h.FS_createPath("/World","Font",!0,!0);h.FS_createPath("/World","Material",
!0,!0);h.FS_createPath("/World/Material","Entity",!0,!0);h.FS_createPath("/World/Material","Landscape",!0,!0);h.FS_createPath("/World","Technique",!0,!0);h.FS_createPath("/World/Technique","Composite",!0,!0);h.FS_createPath("/World/Technique","Debug",!0,!0);h.FS_createPath("/World/Technique","Geometry",!0,!0);h.FS_createPath("/World/Technique","Light",!0,!0);h.FS_createPath("/World/Technique","Sprite",!0,!0);h.FS_createPath("/World/Technique","Typography",!0,!0);h.FS_createPath("/World","World",!0,
!0);for(var r of c.files)h.addRunDependency(`fp ${r.filename}`);h.addRunDependency("datafile_bin/Tileon_Editor.data");h.preloadResults||(h.preloadResults={});h.preloadResults["bin/Tileon_Editor.data"]={Ce:!1};l||=await k;(async function(u){if(!u)throw Error("Loading data file failed.");if(u.constructor.name!==ArrayBuffer.name)throw Error("bad input to processPackageData "+u.constructor.name);u=new Uint8Array(u);for(var v of c.files){var z=v.filename;h.FS_createDataFile(z,null,u.subarray(v.start,v.end),
!0,!0,!0);h.removeRunDependency(`fp ${z}`)}h.removeRunDependency("datafile_bin/Tileon_Editor.data")})(l)}typeof window==="object"?window.encodeURIComponent(window.location.pathname.substring(0,window.location.pathname.lastIndexOf("/"))+"/"):typeof process==="undefined"&&typeof location!=="undefined"&&encodeURIComponent(location.pathname.substring(0,location.pathname.lastIndexOf("/"))+"/");var f=m.locateFile?m.locateFile("Tileon_Editor.data",""):"Tileon_Editor.data",g=c.remote_package_size,k,l=m.getPreloadedPackage&&
m.getPreloadedPackage(f,g);l||(k=d(f,g));m.calledRun?e(m):(m.preRun||(m.preRun=[]),m.preRun.push(e))})({files:[{filename:"/Editor/Fonts/Roboto-Medium.ttf",start:0,end:162588},{filename:"/Editor/Fonts/fa-regular-400.ttf",start:162588,end:222968},{filename:"/Editor/Fonts/fa-solid-900.ttf",start:222968,end:414800},{filename:"/Editor/Technique/Shapes/Circle.vfx",start:414800,end:416022},{filename:"/Editor/Technique/Shapes/Line.vfx",start:416022,end:417221},{filename:"/Editor/Technique/Shapes/Primitive-GLSL.shd",
start:417221,end:421384},{filename:"/Editor/Technique/Shapes/Primitive-HLSL.shd",start:421384,end:425958},{filename:"/Editor/Technique/Shapes/Rect.vfx",start:425958,end:427157},{filename:"/Editor/Technique/Shapes/Ring.vfx",start:427157,end:428377},{filename:"/Editor/Technique/Shapes/RoundedRect.vfx",start:428377,end:429605},{filename:"/Editor/Technique/Typography/MSDF-GLSL.shd",start:429605,end:434120},{filename:"/Editor/Technique/Typography/MSDF-HLSL.shd",start:434120,end:439046},{filename:"/Editor/Technique/Typography/MSDF.vfx",
start:439046,end:440407},{filename:"/Editor/Technique/UI/ImGui-GLSL.shd",start:440407,end:441745},{filename:"/Editor/Technique/UI/ImGui-HLSL.shd",start:441745,end:443618},{filename:"/Editor/Technique/UI/ImGui.vfx",start:443618,end:444841},{filename:"/World/Argentum.tileon",start:444841,end:445027},{filename:"/World/Data/Archetypes.bin",start:445027,end:445696},{filename:"/World/Data/Terrains.bin",start:445696,end:445871},{filename:"/World/Data/Tileset.bin",start:445871,end:446397},{filename:"/World/Data/World.bin",
start:446397,end:446439},{filename:"/World/Font/Roboto.artery",start:446439,end:1211783},{filename:"/World/Material/Entity/Goblin.mtl",start:1211783,end:1211928},{filename:"/World/Material/Entity/Goblin.png",start:1211928,end:1214090},{filename:"/World/Material/Entity/Goblin_Normal.png",start:1214090,end:1227516},{filename:"/World/Material/Entity/Tree.mtl",start:1227516,end:1227602},{filename:"/World/Material/Entity/Tree.png",start:1227602,end:2831890},{filename:"/World/Material/Landscape/56951.mtl",
start:2831890,end:2831977},{filename:"/World/Material/Landscape/56951.png",start:2831977,end:3370638},{filename:"/World/Material/Landscape/6032.mtl",start:3370638,end:3370724},{filename:"/World/Material/Landscape/6032.png",start:3370724,end:3479211},{filename:"/World/Material/Landscape/Grass.mtl",start:3479211,end:3479304},{filename:"/World/Material/Landscape/Grass.png",start:3479304,end:3599213},{filename:"/World/Material/Landscape/Sand.mtl",start:3599213,end:3599305},{filename:"/World/Material/Landscape/Sand.png",
start:3599305,end:3708391},{filename:"/World/Material/Landscape/Water.mtl",start:3708391,end:3708484},{filename:"/World/Material/Landscape/Water.png",start:3708484,end:3831346},{filename:"/World/Technique/Composite/Composite-GLSL.shd",start:3831346,end:3832879},{filename:"/World/Technique/Composite/Composite-HLSL.shd",start:3832879,end:3834926},{filename:"/World/Technique/Composite/Composite.vfx",start:3834926,end:3835833},{filename:"/World/Technique/Debug/Boundary-GLSL.shd",start:3835833,end:3838926},
{filename:"/World/Technique/Debug/Boundary-HLSL.shd",start:3838926,end:3842525},{filename:"/World/Technique/Debug/Boundary.vfx",start:3842525,end:3843404},{filename:"/World/Technique/Debug/Grid-GLSL.shd",start:3843404,end:3846719},{filename:"/World/Technique/Debug/Grid-HLSL.shd",start:3846719,end:3850409},{filename:"/World/Technique/Debug/Grid.vfx",start:3850409,end:3851295},{filename:"/World/Technique/Geometry/Circle.vfx",start:3851295,end:3852518},{filename:"/World/Technique/Geometry/Line.vfx",
start:3852518,end:3853718},{filename:"/World/Technique/Geometry/Primitive-GLSL.shd",start:3853718,end:3858036},{filename:"/World/Technique/Geometry/Primitive-HLSL.shd",start:3858036,end:3862745},{filename:"/World/Technique/Geometry/Rect.vfx",start:3862745,end:3863945},{filename:"/World/Technique/Geometry/Ring.vfx",start:3863945,end:3865166},{filename:"/World/Technique/Geometry/RoundedRect.vfx",start:3865166,end:3866395},{filename:"/World/Technique/Geometry/Sprite-GLSL.shd",start:3866395,end:3869768},
{filename:"/World/Technique/Geometry/Sprite-HLSL.shd",start:3869768,end:3874095},{filename:"/World/Technique/Geometry/SpriteNonOpaque.vfx",start:3874095,end:3875328},{filename:"/World/Technique/Geometry/SpriteNonOpaqueWithNormal.vfx",start:3875328,end:3876655},{filename:"/World/Technique/Geometry/SpriteOpaque.vfx",start:3876655,end:3877920},{filename:"/World/Technique/Geometry/SpriteOpaqueWithNormal.vfx",start:3877920,end:3879246},{filename:"/World/Technique/Light/Glowlight.vfx",start:3879246,end:3880489},
{filename:"/World/Technique/Light/Light-GLSL.shd",start:3880489,end:3884419},{filename:"/World/Technique/Light/Light-HLSL.shd",start:3884419,end:3889194},{filename:"/World/Technique/Light/Skylight-GLSL.shd",start:3889194,end:3891524},{filename:"/World/Technique/Light/Skylight-HLSL.shd",start:3891524,end:3894349},{filename:"/World/Technique/Light/Skylight.vfx",start:3894349,end:3895477},{filename:"/World/Technique/Light/Spotlight.vfx",start:3895477,end:3896753},{filename:"/World/Technique/Sprite/Alpha.vfx",
start:3896753,end:3897871},{filename:"/World/Technique/Sprite/Opaque.vfx",start:3897871,end:3898995},{filename:"/World/Technique/Sprite/Sprite-GLSL.shd",start:3898995,end:3901470},{filename:"/World/Technique/Sprite/Sprite-HLSL.shd",start:3901470,end:3904640},{filename:"/World/Technique/Typography/MSDF-GLSL.shd",start:3904640,end:3909158},{filename:"/World/Technique/Typography/MSDF-HLSL.shd",start:3909158,end:3914523},{filename:"/World/Technique/Typography/MSDF.vfx",start:3914523,end:3915888},{filename:"/World/World/-1_-1.region",
start:3915888,end:3924426},{filename:"/World/World/-1_-2.region",start:3924426,end:3932676},{filename:"/World/World/-1_-3.region",start:3932676,end:3940926},{filename:"/World/World/-1_0.region",start:3940926,end:3949545},{filename:"/World/World/-1_1.region",start:3949545,end:3957793},{filename:"/World/World/-1_2.region",start:3957793,end:3966041},{filename:"/World/World/-2_-1.region",start:3966041,end:3974291},{filename:"/World/World/-2_-2.region",start:3974291,end:3982541},{filename:"/World/World/-2_-3.region",
start:3982541,end:3990791},{filename:"/World/World/-2_0.region",start:3990791,end:3999039},{filename:"/World/World/-2_1.region",start:3999039,end:4007287},{filename:"/World/World/-2_2.region",start:4007287,end:4015535},{filename:"/World/World/-3_-1.region",start:4015535,end:4023785},{filename:"/World/World/-3_-2.region",start:4023785,end:4032035},{filename:"/World/World/-3_-3.region",start:4032035,end:4040434},{filename:"/World/World/-3_0.region",start:4040434,end:4048682},{filename:"/World/World/-3_1.region",
start:4048682,end:4056930},{filename:"/World/World/-3_2.region",start:4056930,end:4065178},{filename:"/World/World/-4_-1.region",start:4065178,end:4073428},{filename:"/World/World/-4_-2.region",start:4073428,end:4081678},{filename:"/World/World/-4_-3.region",start:4081678,end:4089928},{filename:"/World/World/-4_-4.region",start:4089928,end:4098178},{filename:"/World/World/-4_0.region",start:4098178,end:4106426},{filename:"/World/World/-4_1.region",start:4106426,end:4114674},{filename:"/World/World/-4_2.region",
start:4114674,end:4122922},{filename:"/World/World/-5_-2.region",start:4122922,end:4131172},{filename:"/World/World/0_-1.region",start:4131172,end:4139564},{filename:"/World/World/0_-2.region",start:4139564,end:4147812},{filename:"/World/World/0_-3.region",start:4147812,end:4156060},{filename:"/World/World/0_0.region",start:4156060,end:4164546},{filename:"/World/World/0_1.region",start:4164546,end:4172792},{filename:"/World/World/0_2.region",start:4172792,end:4181038},{filename:"/World/World/1_-1.region",
start:4181038,end:4189286},{filename:"/World/World/1_-2.region",start:4189286,end:4197534},{filename:"/World/World/1_-3.region",start:4197534,end:4205782},{filename:"/World/World/1_0.region",start:4205782,end:4214173},{filename:"/World/World/1_1.region",start:4214173,end:4222419},{filename:"/World/World/1_2.region",start:4222419,end:4230665},{filename:"/World/World/2_-1.region",start:4230665,end:4238913},{filename:"/World/World/2_-2.region",start:4238913,end:4247161},{filename:"/World/World/2_-3.region",
start:4247161,end:4255409},{filename:"/World/World/2_0.region",start:4255409,end:4263655},{filename:"/World/World/2_1.region",start:4263655,end:4271901},{filename:"/World/World/2_2.region",start:4271901,end:4280147},{filename:"/World/World/3_-1.region",start:4280147,end:4288395},{filename:"/World/World/3_-2.region",start:4288395,end:4296643},{filename:"/World/World/3_-3.region",start:4296643,end:4304891},{filename:"/World/World/3_0.region",start:4304891,end:4313137},{filename:"/World/World/3_1.region",
start:4313137,end:4321383},{filename:"/World/World/3_2.region",start:4321383,end:4329629},{filename:"/World/World/4_-1.region",start:4329629,end:4337877},{filename:"/World/World/4_-2.region",start:4337877,end:4346125},{filename:"/World/World/4_-3.region",start:4346125,end:4354373},{filename:"/World/World/4_0.region",start:4354373,end:4362619},{filename:"/World/World/4_1.region",start:4362619,end:4370865},{filename:"/World/World/4_2.region",start:4370865,end:4379111},{filename:"/World/World/5_-1.region",
start:4379111,end:4387359},{filename:"/World/World/5_-2.region",start:4387359,end:4395607},{filename:"/World/World/5_-3.region",start:4395607,end:4403855},{filename:"/World/World/5_0.region",start:4403855,end:4412101},{filename:"/World/World/5_1.region",start:4412101,end:4420347},{filename:"/World/World/5_2.region",start:4420347,end:4428593},{filename:"/World/World/6_-1.region",start:4428593,end:4436841},{filename:"/World/World/6_-2.region",start:4436841,end:4445089},{filename:"/World/World/6_-3.region",
start:4445089,end:4453337},{filename:"/World/World/6_0.region",start:4453337,end:4461583},{filename:"/World/World/6_1.region",start:4461583,end:4469829},{filename:"/World/World/6_2.region",start:4469829,end:4478075},{filename:"/World/World/7_2.region",start:4478075,end:4486321}],remote_package_size:4486321})}})();var da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;typeof __filename!="undefined"?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("node:fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.length>1&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);typeof module!="undefined"&&(module.exports=m);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{e.status==200||e.status==0&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),n=console.error.bind(console),na,oa=!1,pa,la=a=>a.startsWith("file://");
function qa(){var a=ra.buffer;p=new Int8Array(a);q=new Int16Array(a);t=new Uint8Array(a);sa=new Uint16Array(a);w=new Int32Array(a);x=new Uint32Array(a);ta=new Float32Array(a);y=new Float64Array(a);A=new BigInt64Array(a);new BigUint64Array(a)}function B(a){m.onAbort?.(a);a=`Aborted(${a})`;n(a);oa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua;
async function va(a){if(!na)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ua&&na)a=new Uint8Array(na);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function wa(a,b){try{var c=await va(a);return await WebAssembly.instantiate(c,b)}catch(d){n(`failed to asynchronously prepare wasm: ${d}`),B(d)}}
async function xa(a){var b=ua;if(!na&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){n(`wasm streaming compile failed: ${d}`),n("falling back to ArrayBuffer instantiation")}return wa(b,a)}class ya{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var q,w,A,p,ta,y,sa,x,t,za=a=>{for(;a.length>0;)a.shift()(m)},Aa=[],Ba=[],Ca=()=>{var a=m.preRun.shift();Ba.push(a)},Da=0,Ea=null,Fa=()=>{Da--;m.monitorRunDependencies?.(Da);if(Da==0&&Ea){var a=Ea;Ea=null;a()}},Ga=()=>{Da++;m.monitorRunDependencies?.(Da)},Ha=!0,Ia=()=>{if(ca){var a=require("node:crypto");return b=>a.randomFillSync(b)}return b=>(crypto.getRandomValues(b),0)},Ja=a=>(Ja=Ia())(a),Ka=(a,b)=>{for(var c=0,d=a.length-1;d>=0;d--){var e=a[d];e==="."?a.splice(d,1):e===".."?(a.splice(d,1),c++):
c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},La=a=>{var b=a.charAt(0)==="/",c=a.slice(-1)==="/";(a=Ka(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ma=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Na=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Oa=(...a)=>{for(var b="",c=!1,d=a.length-1;d>=-1&&!c;d--){c=d>=0?a[d]:"/";if(typeof c!="string")throw new TypeError("Arguments to path.resolve must be strings");
if(!c)return"";b=c+"/"+b;c=c.charAt(0)==="/"}b=Ka(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Pa=globalThis.TextDecoder&&new TextDecoder,D=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(d-b>16&&a.buffer&&Pa)return Pa.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if((e&224)==192)c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=(e&240)==224?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;e<65536?c+=String.fromCharCode(e):(e-=65536,
c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Qa=[],Ra=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},E=(a,b,c,d)=>{if(!(d>0))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(g<=127){if(c>=d)break;b[c++]=g}else if(g<=2047){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(g<=65535){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=
128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Sa=a=>{var b=Array(Ra(a)+1);a=E(a,b,0,b.length);b.length=a;return b},Ta=[];function Ua(a,b){Ta[a]={input:[],output:[],xc:b};Va(a,Wa)}
var Wa={open(a){var b=Ta[a.node.rdev];if(!b)throw new G(43);a.tty=b;a.seekable=!1},close(a){a.tty.xc.fsync(a.tty)},fsync(a){a.tty.xc.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.xc.Hd)throw new G(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.xc.Hd(a.tty)}catch(k){throw new G(29);}if(g===void 0&&e===0)throw new G(6);if(g===null||g===void 0)break;e++;b[c+f]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.xc.ld)throw new G(60);try{for(var e=0;e<d;e++)a.tty.xc.ld(a.tty,b[c+e])}catch(f){throw new G(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},Xa={Hd(){a:{if(!Qa.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}c>0&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),a!==null&&(a+="\n"));if(!a){a=null;break a}Qa=Sa(a)}a=Qa.shift()}return a},ld(a,b){b===null||b===10?(ma(D(a.output)),a.output=[]):b!=0&&a.output.push(b)},fsync(a){a.output?.length>
0&&(ma(D(a.output)),a.output=[])},Yd(){return{pe:25856,re:5,oe:191,qe:35387,ne:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Zd(){return 0},$d(){return[24,80]}},Ya={ld(a,b){b===null||b===10?(n(D(a.output)),a.output=[]):b!=0&&a.output.push(b)},fsync(a){a.output?.length>0&&(n(D(a.output)),a.output=[])}},J={sc:null,rc(){return J.createNode(null,"/",16895,0)},createNode(a,b,c,d){if((c&61440)===24576||(c&61440)===4096)throw new G(63);J.sc||(J.sc={dir:{node:{vc:J.ac.vc,
zc:J.ac.zc,lookup:J.ac.lookup,Wc:J.ac.Wc,rename:J.ac.rename,unlink:J.ac.unlink,rmdir:J.ac.rmdir,readdir:J.ac.readdir,symlink:J.ac.symlink},stream:{qc:J.bc.qc}},file:{node:{vc:J.ac.vc,zc:J.ac.zc},stream:{qc:J.bc.qc,read:J.bc.read,write:J.bc.write,jd:J.bc.jd,Ld:J.bc.Ld}},link:{node:{vc:J.ac.vc,zc:J.ac.zc,readlink:J.ac.readlink},stream:{}},xd:{node:{vc:J.ac.vc,zc:J.ac.zc},stream:Za}});c=$a(a,b,c,d);K(c.mode)?(c.ac=J.sc.dir.node,c.bc=J.sc.dir.stream,c.dc={}):(c.mode&61440)===32768?(c.ac=J.sc.file.node,
c.bc=J.sc.file.stream,c.hc=0,c.dc=J.Td??(J.Td=new Uint8Array(0))):(c.mode&61440)===40960?(c.ac=J.sc.link.node,c.bc=J.sc.link.stream):(c.mode&61440)===8192&&(c.ac=J.sc.xd.node,c.bc=J.sc.xd.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.dc[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},ac:{vc(a){var b={};b.dev=(a.mode&61440)===8192?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;K(a.mode)?b.size=4096:(a.mode&61440)===32768?b.size=a.hc:(a.mode&61440)===40960?b.size=a.link.length:
b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},zc(a,b){for(var c of["mode","atime","mtime","ctime"])b[c]!=null&&(a[c]=b[c]);b.size!==void 0&&(b=b.size,a.hc!=b&&(c=a.dc,a.dc=new Uint8Array(b),a.dc.set(c.subarray(0,Math.min(b,a.hc))),a.hc=b))},lookup(){J.cd||(J.cd=new G(44),J.cd.stack="<generic error, no stack>");throw J.cd;},Wc(a,b,c,d){return J.createNode(a,b,c,d)},rename(a,b,c){try{var d=ab(b,c)}catch(f){}if(d){if(K(a.mode))for(var e in d.dc)throw new G(55);
bb(d)}delete a.parent.dc[a.name];b.dc[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.dc[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=ab(a,b),d;for(d in c.dc)throw new G(55);delete a.dc[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.dc)]},symlink(a,b,c){a=J.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if((a.mode&61440)!==40960)throw new G(28);return a.link}},bc:{read(a,b,c,d,e){if(e>=a.node.hc)return 0;d=Math.min(a.node.hc-
e,d);b.set(a.node.dc.subarray(e,e+d),c);return d},write(a,b,c,d,e,f){b.buffer===p.buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(f)a.dc=b.subarray(c,c+d),a.hc=d;else if(a.hc===0&&e===0)a.dc=b.slice(c,c+d),a.hc=d;else{f=e+d;var g=a.dc.length;g>=f||(f=Math.max(f,g*(g<1048576?2:1.125)>>>0),g&&(f=Math.max(f,256)),g=a.dc.subarray(0,a.hc),a.dc=new Uint8Array(f),a.dc.set(g));a.dc.set(b.subarray(c,c+d),e);a.hc=Math.max(a.hc,e+d)}return d},qc(a,b,c){c===1?b+=a.position:c===2&&(a.node.mode&
61440)===32768&&(b+=a.node.hc);if(b<0)throw new G(28);return b},jd(a,b,c,d,e){if((a.node.mode&61440)!==32768)throw new G(43);a=a.node.dc;if(e&2||a.buffer!==p.buffer){d=!0;B();e=void 0;if(!e)throw new G(48);if(a){if(c>0||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);p.set(a,e)}}else d=!1,e=a.byteOffset;return{Me:e,ke:d}},Ld(a,b,c,d){J.bc.write(a,b,0,d,c,!1);return 0}}},cb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},db=async a=>{a=await ja(a);return new Uint8Array(a)},
eb=[],hb=async(a,b)=>{typeof fb!="undefined"&&gb();for(var c of eb)if(c.canHandle(b))return c.handle(a,b);return a},ib=null,jb={},kb=[],lb=1,mb=null,nb=!1,ob=!0,G=class{name="ErrnoError";constructor(a){this.cc=a}},pb=class{shared={};node=null;get flags(){return this.shared.flags}set flags(a){this.shared.flags=a}get position(){return this.shared.position}set position(a){this.shared.position=a}},qb=class{ac={};bc={};Gc=null;constructor(a,b,c,d){a||=this;this.parent=a;this.rc=a.rc;this.id=lb++;this.name=
b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return(this.mode&365)===365}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return(this.mode&146)===146}set write(a){a?this.mode|=146:this.mode&=-147}get be(){return K(this.mode)}get ae(){return(this.mode&61440)===8192}};
function M(a,b={}){if(!a)throw new G(44);b.ed??(b.ed=!0);a.charAt(0)==="/"||(a="//"+a);var c=0;a:for(;c<40;c++){a=a.split("/").filter(k=>!!k);for(var d=ib,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if(a[f]!==".")if(a[f]==="..")if(e=Ma(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=La(e+"/"+a[f]);try{d=ab(d,a[f])}catch(k){if(k?.cc===44&&g&&b.ee)return{path:e};throw k;}!d.Gc||g&&!b.ed||(d=d.Gc.root);if((d.mode&61440)===40960&&(!g||b.Nc)){if(!d.ac.readlink)throw new G(52);
d=d.ac.readlink(d);d.charAt(0)==="/"||(d=Ma(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new G(32);}function rb(a){for(var b;;){if(a===a.parent)return a=a.rc.Kd,b?a[a.length-1]!=="/"?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function sb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%mb.length}
function bb(a){var b=sb(a.parent.id,a.name);if(mb[b]===a)mb[b]=a.Hc;else for(b=mb[b];b;){if(b.Hc===a){b.Hc=a.Hc;break}b=b.Hc}}function ab(a,b){var c=K(a.mode)?(c=tb(a,"x"))?c:a.ac.lookup?0:2:54;if(c)throw new G(c);for(c=mb[sb(a.id,b)];c;c=c.Hc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ac.lookup(a,b)}function $a(a,b,c,d){a=new qb(a,b,c,d);b=sb(a.parent.id,a.name);a.Hc=mb[b];return mb[b]=a}function K(a){return(a&61440)===16384}
function tb(a,b){return ob?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function ub(a,b){if(!K(a.mode))return 54;try{return ab(a,b),20}catch(c){}return tb(a,"wx")}function vb(a,b,c){try{var d=ab(a,b)}catch(e){return e.cc}if(a=tb(a,"wx"))return a;if(c){if(!K(d.mode))return 54;if(d===d.parent||rb(d)==="/")return 10}else if(K(d.mode))return 31;return 0}function wb(a,b){if(!a)throw new G(b);return a}
function xb(a){a=kb[a];if(!a)throw new G(8);return a}function yb(a,b=-1){a=Object.assign(new pb,a);if(b==-1)a:{for(b=0;b<=4096;b++)if(!kb[b])break a;throw new G(33);}a.fd=b;return kb[b]=a}function zb(a,b=-1){a=yb(a,b);a.bc?.ye?.(a);return a}function Ab(a,b){var c=void 0,d=c?null:a;c??=a.ac.zc;wb(c,63);try{c(d,b)}catch(e){if(e instanceof RangeError)throw new G(22);throw e;}}var Za={open(a){a.bc=jb[a.node.rdev].bc;a.bc.open?.(a)},qc(){throw new G(70);}};function Va(a,b){jb[a]={bc:b}}
function Bb(a,b){var c=b==="/";if(c&&ib)throw new G(10);if(!c&&b){var d=M(b,{ed:!1});b=d.path;d=d.node;if(d.Gc)throw new G(10);if(!K(d.mode))throw new G(54);}b={type:a,Je:{},Kd:b,de:[]};a=a.rc(b);a.rc=b;b.root=a;c?ib=a:d&&(d.Gc=b,d.rc&&d.rc.de.push(b));return a}function Cb(a,b,c){var d=M(a,{parent:!0}).node;a=Na(a);if(!a)throw new G(28);if(a==="."||a==="..")throw new G(20);var e=ub(d,a);if(e)throw new G(e);if(!d.ac.Wc)throw new G(63);return d.ac.Wc(d,a,b,c)}
function Db(a,b=438){return Cb(a,b&4095|32768,0)}function N(a,b=511){return Cb(a,b&1023|16384,0)}function Eb(a,b,c){typeof c=="undefined"&&(c=b,b=438);return Cb(a,b|8192,c)}function Fb(a,b){if(!Oa(a))throw new G(44);var c=M(b,{parent:!0}).node;if(!c)throw new G(44);b=Na(b);var d=ub(c,b);if(d)throw new G(d);if(!c.ac.symlink)throw new G(63);c.ac.symlink(c,b,a)}
function Gb(a){var b=M(a,{parent:!0}).node;a=Na(a);var c=ab(b,a),d=vb(b,a,!0);if(d)throw new G(d);if(!b.ac.rmdir)throw new G(63);if(c.Gc)throw new G(10);b.ac.rmdir(b,a);bb(c)}function Hb(a){var b=M(a,{parent:!0}).node;if(!b)throw new G(44);a=Na(a);var c=ab(b,a),d=vb(b,a,!1);if(d)throw new G(d);if(!b.ac.unlink)throw new G(63);if(c.Gc)throw new G(10);b.ac.unlink(b,a);bb(c)}function Ib(a,b){a=M(a,{Nc:!b}).node;return wb(a.ac.vc,63)(a)}
function Jb(a,b){a=typeof a=="string"?M(a,{Nc:!0}).node:a;Ab(a,{mode:b&4095|a.mode&-4096,ctime:Date.now(),xe:void 0})}
function Kb(a,b,c=438){if(a==="")throw new G(44);if(typeof b=="string"){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if(typeof d=="undefined")throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if(typeof a=="object")d=a;else{var e=a.endsWith("/");var f=M(a,{Nc:!(b&131072),ee:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new G(20);}else{if(e)throw new G(31);d=Cb(a,c|511,0);f=!0}if(!d)throw new G(44);(d.mode&61440)===8192&&(b&=-513);if(b&65536&&!K(d.mode))throw new G(54);
if(!f&&(d?(d.mode&61440)===40960?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=K(d.mode)&&(e!=="r"||b&576)?31:tb(d,e)):e=44,e))throw new G(e);if(b&512&&!f){e=d;e=typeof e=="string"?M(e,{Nc:!0}).node:e;if(K(e.mode))throw new G(31);if((e.mode&61440)!==32768)throw new G(28);if(a=tb(e,"w"))throw new G(a);Ab(e,{size:0,timestamp:Date.now()})}b=yb({node:d,path:rb(d),flags:b&-131713,seekable:!0,position:0,bc:d.bc,ie:[],error:!1});b.bc.open&&b.bc.open(b);f&&Jb(d,c&511);return b}
function Lb(a){if(a.fd===null)throw new G(8);a.Dc&&(a.Dc=null);try{a.bc.close&&a.bc.close(a)}catch(b){throw b;}finally{kb[a.fd]=null}a.fd=null}function Mb(a,b,c){if(a.fd===null)throw new G(8);if(!a.seekable||!a.bc.qc)throw new G(70);if(c!=0&&c!=1&&c!=2)throw new G(28);a.position=a.bc.qc(a,b,c);a.ie=[];return a.position}
function Nb(a,b,c,d,e,f){if(d<0||e<0)throw new G(28);if(a.fd===null)throw new G(8);if((a.flags&2097155)===0)throw new G(8);if(K(a.node.mode))throw new G(31);if(!a.bc.write)throw new G(28);a.seekable&&a.flags&1024&&Mb(a,0,2);var g=typeof e!="undefined";if(!g)e=a.position;else if(!a.seekable)throw new G(70);b=a.bc.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function Ob(a,b){a=typeof a=="string"?a:rb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=La(a+"/"+c);try{N(d)}catch(e){if(e.cc!=20)throw e;}a=d}}return d}function Pb(a,b,c,d){a=La((typeof a=="string"?a:rb(a))+"/"+b);return Db(a,cb(c,d))}function Qb(a,b,c,d,e,f){var g=b;a&&(a=typeof a=="string"?a:rb(a),g=b?La(a+"/"+b):a);a=cb(d,e);g=Db(g,a);c&&(typeof c=="string"&&(c=Sa(c)),c.subarray||(c=new Uint8Array(c)),Jb(g,a|146),b=Kb(g,577),Nb(b,c,0,c.length,0,f),Lb(b),Jb(g,a))}
function Rb(a,b,c,d){a=La((typeof a=="string"?a:rb(a))+"/"+b);b=cb(!!c,!!d);Rb.Jd??(Rb.Jd=64);var e=Rb.Jd++<<8|0;Va(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,k,l){for(var h=0,r=0;r<l;r++){try{var u=c()}catch(v){throw new G(29);}if(u===void 0&&h===0)throw new G(6);if(u===null||u===void 0)break;h++;g[k+r]=u}h&&(f.node.atime=Date.now());return h},write(f,g,k,l){for(var h=0;h<l;h++)try{d(g[k+h])}catch(r){throw new G(29);}l&&(f.node.mtime=f.node.ctime=Date.now());return h}});
return Eb(a,b,e)}function Sb(a){if(!(a.ae||a.be||a.link||a.dc))if(globalThis.XMLHttpRequest)B("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.dc=ka(a.url)}catch(b){throw new G(29);}}
function Tb(a,b,c,d,e){class f{bd=!1;Cc=[];$c=void 0;Dd=0;Bd=0;get(h){if(!(h>this.length-1||h<0)){var r=h%this.chunkSize;return this.$c(h/this.chunkSize|0)[r]}}Wd(h){this.$c=h}Gd(){var h=new XMLHttpRequest;h.open("HEAD",c,!1);h.send(null);h.status>=200&&h.status<300||h.status===304||B("Couldn't load "+c+". Status: "+h.status);var r=Number(h.getResponseHeader("Content-length")),u,v=(u=h.getResponseHeader("Accept-Ranges"))&&u==="bytes";h=(u=h.getResponseHeader("Content-Encoding"))&&u==="gzip";var z=
1048576;v||(z=r);var C=this;C.Wd(I=>{var H=I*z,F=(I+1)*z-1;F=Math.min(F,r-1);if(typeof C.Cc[I]=="undefined"){var Z=C.Cc;H>F&&B(`invalid range (${H}, ${F}) or no bytes requested!`);F>r-1&&B(`only ${r} bytes available! programmer error!`);var L=new XMLHttpRequest;L.open("GET",c,!1);r!==z&&L.setRequestHeader("Range","bytes="+H+"-"+F);L.responseType="arraybuffer";L.overrideMimeType&&L.overrideMimeType("text/plain; charset=x-user-defined");L.send(null);L.status>=200&&L.status<300||L.status===304||B("Couldn't load "+
c+". Status: "+L.status);H=L.response!==void 0?new Uint8Array(L.response||[]):Sa(L.responseText??"");Z[I]=H}typeof C.Cc[I]=="undefined"&&B("doXHR failed!");return C.Cc[I]});if(h||!r)z=r=1,z=r=this.$c(0).length,ma("LazyFiles on gzip forces download of the whole file when length is accessed");this.Dd=r;this.Bd=z;this.bd=!0}get length(){this.bd||this.Gd();return this.Dd}get chunkSize(){this.bd||this.Gd();return this.Bd}}if(globalThis.XMLHttpRequest){ba||B("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");
var g=new f;var k=void 0}else k=c,g=void 0;var l=Pb(a,b,d,e);g?l.dc=g:k&&(l.dc=null,l.url=k);Object.defineProperties(l,{hc:{get:function(){return this.dc.length}}});a={};for(let [h,r]of Object.entries(l.bc))a[h]=(...u)=>{Sb(l);return r(...u)};a.read=(h,r,u,v,z)=>{Sb(l);h=h.node.dc;if(z>=h.length)r=0;else{v=Math.min(h.length-z,v);if(h.slice)for(var C=0;C<v;C++)r[u+C]=h[z+C];else for(C=0;C<v;C++)r[u+C]=h.get(z+C);r=v}return r};a.jd=()=>{Sb(l);B();throw new G(48);};l.bc=a;return l}var O={};
function Ub(a,b){if(a.type===1&&a.fc)throw new G(53);var c=a.Ic.shift();if(!c){if(a.type===1){a=a.yc[a.mc+":"+a.nc];if(!a)throw new G(53);if(a.socket.readyState===a.socket.CLOSING||a.socket.readyState===a.socket.CLOSED)return null}throw new G(6);}var d=c.data.byteLength||c.data.length,e=c.data.byteOffset||0,f=c.data.buffer||c.data;b=Math.min(b,d);var g={buffer:new Uint8Array(f,e,b),ec:c.ec,port:c.port};a.type===1&&b<d&&(c.data=new Uint8Array(f,e+b,d-b),a.Ic.unshift(c));return g}
function Vb(a,b,c,d,e,f){if(a.type===2){if(e===void 0||f===void 0)e=a.mc,f=a.nc;if(e===void 0||f===void 0)throw new G(17);}else e=a.mc,f=a.nc;var g=a.yc[e+":"+f];if(a.type===1&&(!g||g.socket.readyState===g.socket.CLOSING||g.socket.readyState===g.socket.CLOSED))throw new G(53);ArrayBuffer.isView(b)&&(c+=b.byteOffset,b=b.buffer);b=b.slice(c,c+d);if(!g||g.socket.readyState!==g.socket.OPEN)return a.type===2&&(g&&g.socket.readyState!==g.socket.CLOSING&&g.socket.readyState!==g.socket.CLOSED||(g=Wb(a,e,
f))),g.Yc.push(b),d;try{return g.socket.send(b),d}catch(k){throw new G(28);}}
function Xb(a,b){function c(){a.yd=!1;P.emit("open",a.stream.fd);try{for(var f=b.Yc.shift();f;)b.socket.send(f),f=b.Yc.shift()}catch(g){b.socket.close()}}function d(f){if(typeof f=="string")f=(new TextEncoder).encode(f);else{if(f.byteLength==0)return;f=new Uint8Array(f)}var g=e;e=!1;g&&f.length===10&&f[0]===255&&f[1]===255&&f[2]===255&&f[3]===255&&f[4]===112&&f[5]===111&&f[6]===114&&f[7]===116?(f=f[8]<<8|f[9],delete a.yc[b.ec+":"+b.port],b.port=f,a.yc[b.ec+":"+b.port]=b):(a.Ic.push({ec:b.ec,port:b.port,
data:f}),P.emit("message",a.stream.fd))}var e=!0;ca?(b.socket.on("open",c),b.socket.on("message",(f,g)=>{g&&d((new Uint8Array(f)).buffer)}),b.socket.on("close",()=>P.emit("close",a.stream.fd)),b.socket.on("error",()=>{a.error=14;P.emit("error",[a.stream.fd,a.error,"ECONNREFUSED: Connection refused"])})):(b.socket.onopen=c,b.socket.onclose=()=>P.emit("close",a.stream.fd),b.socket.onmessage=f=>d(f.data),b.socket.onerror=()=>{a.error=14;P.emit("error",[a.stream.fd,a.error,"ECONNREFUSED: Connection refused"])})}
function Wb(a,b,c){if(typeof b=="object"){var d=b;c=b=null}if(d)if(d._socket)b=d._socket.remoteAddress,c=d._socket.remotePort;else{c=/ws[s]?:\/\/([^:]+):(\d+)/.exec(d.url);if(!c)throw Error("WebSocket URL must be in the format ws(s)://address:port");b=c[1];c=parseInt(c[2],10)}else try{var e="ws://".replace("#","//"),f="binary",g=void 0;P.Lc.url&&(e=P.Lc.url);P.Lc.subprotocol?f=P.Lc.subprotocol:P.Lc.subprotocol===null&&(f="null");if(e==="ws://"||e==="wss://"){var k=b.split("/");e=e+k[0]+":"+c+"/"+
k.slice(1).join("/")}f!=="null"&&(g=f=f.replace(/^ +| +$/g,"").split(/ *, */));d=new (ca?require("ws"):WebSocket)(e,g);d.binaryType="arraybuffer"}catch(l){throw new G(23);}b={ec:b,port:c,socket:d,Yc:[]};a.yc[b.ec+":"+b.port]=b;Xb(a,b);a.type===2&&typeof a.Kc!="undefined"&&b.Yc.push(new Uint8Array([255,255,255,255,112,111,114,116,(a.Kc&65280)>>8,a.Kc&255]));return b}
var P={Lc:{},vd:{},on(a,b){P.vd[a]=b},emit(a,b){P.vd[a]?.(b)},rc(){P.Lc=m.websocket||{};var a;((a=m).websocket??(a.websocket={})).on=P.on;return $a(null,"/",16895,0)},createSocket(a,b,c){if(a!=2)throw new G(5);b&=-526337;if(b!=1&&b!=2)throw new G(28);if(b==1&&c&&c!=6)throw new G(66);a={family:a,type:b,protocol:c,fc:null,error:null,yc:{},pending:[],Ic:[],Ec:P.je};b=P.Zc();c=$a(P.root,b,49152,0);c.Jc=a;b=yb({path:b,node:c,flags:2,seekable:!1,bc:P.bc});a.stream=b;return a},bc:{Nd(a){a=a.node.Jc;return a.Ec.Nd(a)},
Sc(a,b,c){a=a.node.Jc;return a.Ec.Sc(a,b,c)},read(a,b,c,d){a=Ub(a.node.Jc,d);if(!a)return 0;b.set(a.buffer,c);return a.buffer.length},write(a,b,c,d){return Vb(a.node.Jc,b,c,d)},close(a){a=a.node.Jc;a.Ec.close(a)}},Zc(){P.Zc.current||(P.Zc.current=0);return`socket[${P.Zc.current++}]`},je:{Nd(a){if(a.type===1&&a.fc)return a.pending.length?65:0;var b=0,c=a.type===1?a.yc[a.mc+":"+a.nc]:null;if(a.Ic.length||!c||c&&c.socket.readyState===c.socket.CLOSING||c&&c.socket.readyState===c.socket.CLOSED)b|=65;if(!c||
c&&c.socket.readyState===c.socket.OPEN)b|=4;if(c&&c.socket.readyState===c.socket.CLOSING||c&&c.socket.readyState===c.socket.CLOSED)b=a.yd?b|4:b|16;return b},Sc(a,b,c){switch(b){case 21531:return b=0,a.Ic.length&&(b=a.Ic[0].data.length),w[c>>2]=b,0;case 21537:return a.stream.flags=w[c>>2]?a.stream.flags|2048:a.stream.flags&-2049,0;default:return 28}},close(a){if(a.fc){try{a.fc.close()}catch(c){}a.fc=null}for(var b of Object.values(a.yc)){try{b.socket.close()}catch(c){}delete a.yc[b.ec+":"+b.port]}return 0},
bind(a,b,c){if(typeof a.md!="undefined"||typeof a.Kc!="undefined")throw new G(28);a.md=b;a.Kc=c;if(a.type===2){a.fc&&(a.fc.close(),a.fc=null);try{a.Ec.listen(a,0)}catch(d){if(d.name!=="ErrnoError")throw d;if(d.cc!==138)throw d;}}},connect(a,b,c){if(a.fc)throw new G(138);if(typeof a.mc!="undefined"&&typeof a.nc!="undefined"){var d=a.yc[a.mc+":"+a.nc];if(d){if(d.socket.readyState===d.socket.CONNECTING)throw new G(7);throw new G(30);}}b=Wb(a,b,c);a.mc=b.ec;a.nc=b.port;a.yd=!0},listen(a){if(!ca)throw new G(138);
if(a.fc)throw new G(28);var b=require("ws").Server;a.fc=new b({host:a.md,port:a.Kc});P.emit("listen",a.stream.fd);a.fc.on("connection",c=>{if(a.type===1){var d=P.createSocket(a.family,a.type,a.protocol);c=Wb(d,c);d.mc=c.ec;d.nc=c.port;a.pending.push(d);P.emit("connection",d.stream.fd)}else Wb(a,c),P.emit("connection",a.stream.fd)});a.fc.on("close",()=>{P.emit("close",a.stream.fd);a.fc=null});a.fc.on("error",()=>{a.error=23;P.emit("error",[a.stream.fd,a.error,"EHOSTUNREACH: Host is unreachable"])})},
accept(a){if(!a.fc||!a.pending.length)throw new G(28);var b=a.pending.shift();b.stream.flags=a.stream.flags;return b},Fe(a,b){if(b){if(a.mc===void 0||a.nc===void 0)throw new G(53);b=a.mc;a=a.nc}else b=a.md||0,a=a.Kc||0;return{ec:b,port:a}}}},Yb=a=>{a=(a=kb[a])&&(a.node.mode&49152)===49152?a.node.Jc:null;if(!a)throw new G(8);return a},Zb=a=>{a=a.split(".");for(var b=0;b<4;b++){var c=Number(a[b]);if(isNaN(c))return null;a[b]=c}return(a[0]|a[1]<<8|a[2]<<16|a[3]<<24)>>>0},ac=a=>{var b,c,d=[];if(!/^((?=.*::)(?!.*::.+::)(::)?([\dA-F]{1,4}:(:|\b)|){5}|([\dA-F]{1,4}:){6})((([\dA-F]{1,4}((?!\3)::|:\b|$))|(?!\2\3)){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})$/i.test(a))return null;
if(a==="::")return[0,0,0,0,0,0,0,0];a=a.startsWith("::")?a.replace("::","Z:"):a.replace("::",":Z:");a.indexOf(".")>0?(a=a.replace(RegExp("[.]","g"),":"),a=a.split(":"),a[a.length-4]=Number(a[a.length-4])+Number(a[a.length-3])*256,a[a.length-3]=Number(a[a.length-2])+Number(a[a.length-1])*256,a=a.slice(0,a.length-2)):a=a.split(":");for(b=c=0;b<a.length;b++)if(typeof a[b]=="string")if(a[b]==="Z"){for(c=0;c<8-a.length+1;c++)d[b+c]=0;--c}else d[b+c]=$b(parseInt(a[b],16));else d[b+c]=a[b];return[d[1]<<
16|d[0],d[3]<<16|d[2],d[5]<<16|d[4],d[7]<<16|d[6]]},bc=(a,b,c,d,e)=>{switch(b){case 2:c=Zb(c);t.fill(0,a,a+16);e&&(w[e>>2]=16);q[a>>1]=b;w[a+4>>2]=c;q[a+2>>1]=$b(d);break;case 10:c=ac(c),t.fill(0,a,a+28),e&&(w[e>>2]=28),w[a>>2]=b,w[a+8>>2]=c[0],w[a+12>>2]=c[1],w[a+16>>2]=c[2],w[a+20>>2]=c[3],q[a+2>>1]=$b(d)}},cc=1,dc={},ec={};function fc(a){var b=Zb(a);if(b!==null)return a;b=ac(a);if(b!==null)return a;dc[a]?b=dc[a]:(b=cc++,b="172.29."+(b&255)+"."+(b&65280),ec[b]=a,dc[a]=b);return b}
var hc=a=>(a&255)+"."+(a>>8&255)+"."+(a>>16&255)+"."+(a>>24&255),jc=(a,b)=>{var c=q[a>>1],d=ic(sa[a+2>>1]);switch(c){case 2:if(b!==16)return{cc:28};var e=w[a+4>>2];e=hc(e);break;case 10:if(b!==28)return{cc:28};e=[w[a+8>>2],w[a+12>>2],w[a+16>>2],w[a+20>>2]];a:{a="";var f,g=b=0,k=0,l=0;e=[e[0]&65535,e[0]>>16,e[1]&65535,e[1]>>16,e[2]&65535,e[2]>>16,e[3]&65535,e[3]>>16];var h=!0;for(f=0;f<5;f++)if(e[f]!==0){h=!1;break}if(h){f=hc(e[6]|e[7]<<16);if(e[5]===-1){e="::ffff:"+f;break a}if(e[5]===0){f==="0.0.0.0"&&
(f="");f==="0.0.0.1"&&(f="1");e="::"+f;break a}}for(f=0;f<8;f++)e[f]===0&&(f-g>1&&(l=0),g=f,l++),l>b&&(b=l,k=f-b+1);for(f=0;f<8;f++)b>1&&e[f]===0&&f>=k&&f<k+b?f===k&&(a+=":",k===0&&(a+=":")):(a+=Number(ic(e[f]&65535)).toString(16),a+=f<7?":":"");e=a}break;default:return{cc:5}}return{family:c,ec:e,port:d}},kc=(a,b)=>{a=jc(a,b);if(a.cc)throw new G(a.cc);b=a.ec;a.ec=(ec[b]?ec[b]:null)||a.ec;return a},mc=()=>{var a=w[+lc>>2];lc+=4;return a};
function nc(a,b,c){if(b.charAt(0)==="/")return b;a=a===-100?"/":xb(a).path;if(b.length==0){if(!c)throw new G(44);return a}return a+"/"+b}
function oc(a,b){x[a>>2]=b.dev;x[a+4>>2]=b.mode;x[a+8>>2]=b.nlink;x[a+12>>2]=b.uid;x[a+16>>2]=b.gid;x[a+20>>2]=b.rdev;A[a+24>>3]=BigInt(b.size);w[a+32>>2]=4096;w[a+36>>2]=b.blocks;var c=b.atime.getTime(),d=b.mtime.getTime(),e=b.ctime.getTime();A[a+40>>3]=BigInt(Math.floor(c/1E3));x[a+48>>2]=c%1E3*1E3*1E3;A[a+56>>3]=BigInt(Math.floor(d/1E3));x[a+64>>2]=d%1E3*1E3*1E3;A[a+72>>3]=BigInt(Math.floor(e/1E3));x[a+80>>2]=e%1E3*1E3*1E3;A[a+88>>3]=BigInt(b.ino);return 0}
var lc=void 0,pc=[0,31,60,91,121,152,182,213,244,274,305,335],qc=[0,31,59,90,120,151,181,212,243,273,304,334],rc=[],sc=(a,b)=>{rc.length=0;for(var c;c=t[a++];){var d=c!=105;d&=c!=112;b+=d&&b%8?4:0;rc.push(c==112?x[b>>2]:c==106?A[b>>3]:c==105?w[b>>2]:y[b>>3]);b+=d?8:4}return rc},Cc=(a,b)=>{tc=a;uc=b;if(vc)if(wc||=!0,a==0)xc=function(){setTimeout(yc,Math.max(0,zc+b-performance.now())|0)};else if(a==1)xc=function(){Ac(yc)};else{if(!Bc)if(globalThis.scheduler)Bc=scheduler.postTask.bind(scheduler);else if(globalThis.setImmediate)Bc=
setImmediate;else{var c=[];addEventListener("message",d=>{d.data==="setimmediate"&&(d.stopPropagation(),c.shift()())},!0);Bc=d=>{c.push(d);ba?postMessage("setimmediate"):postMessage("setimmediate","*")}}xc=function(){Bc(yc)}}},Dc=a=>{pa=a;Ha||(m.onExit?.(a),oa=!0);fa(a,new ya(a))},Ec=a=>{a instanceof ya||a=="unwind"||fa(1,a)},Fc=()=>{if(!Ha)try{var a=pa;pa=a;Dc(a)}catch(b){Ec(b)}},Pc=(a,b,c,d,e)=>{function f(){return g<Gc?(Fc(),!1):!0}vc=a;Hc=d;var g=Gc;wc=!1;yc=function(){if(!oa)if(Ic.length>0){var k=
Ic.shift();k.De(k.le);if(Jc){var l=Jc,h=l%1==0?l-1:Math.floor(l);Jc=k.te?h:(8*l+(h+.5))/9}m.setStatus&&(k=m.statusMessage||"Please wait...",l=Jc??0,h=Kc.ze??0,l?l<h?m.setStatus("{message} ({expected - remaining}/{expected})"):m.setStatus(k):m.setStatus(""));f()&&setTimeout(yc,0)}else if(f())if(Lc=Lc+1|0,tc==1&&uc>1&&Lc%uc!=0)xc();else{tc==0&&(zc=performance.now());a:if(!oa){for(k of Mc)if(k()===!1)break a;Nc(a);for(l of Oc)l()}f()&&xc()}};e||(b>0?Cc(0,1E3/b):Cc(1,1),xc());if(c)throw"unwind";},Nc=
a=>{if(!oa)try{a()}catch(b){Ec(b)}finally{Fc()}},wc=!1,xc=null,Gc=0,vc=null,Hc=0,tc=0,uc=0,Lc=0,Ic=[],Mc=[],Oc=[];function Qc(){xc=null;Gc++}var Rc=0;function Ac(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(Rc===0)Rc=b+1E3/60;else for(;b+2>=Rc;)Rc+=1E3/60;setTimeout(a,Math.max(Rc-b,0))}}var Kc={},zc,yc,Bc,Jc;function Sc(a){var b=Q.jc[a];b.target.removeEventListener(b.kc,b.Fd,b.tc);Q.jc.splice(a,1)}
function Tc(a){function b(e,f){if(e.length!=f.length)return!1;for(var g in e)if(e[g]!=f[g])return!1;return!0}var c=Uc,d;for(d of Q.Ac)if(d.od==c&&b(d.ud,a))return;Q.Ac.push({od:c,Od:1,ud:a});Q.Ac.sort((e,f)=>e.Od-f.Od)}function Vc(){var a=Uc;Q.Ac=Q.Ac.filter(b=>b.od!=a)}function Wc(){if(navigator.userActivation?navigator.userActivation.isActive:Q.Rc&&Q.zd.Pc){var a=Q.Ac;Q.Ac=[];for(var b of a)b.od(...b.ud)}}
function Xc(a){if(!a.target)return-4;if(a.lc)a.Fd=function(c){++Q.Rc;Q.zd=a;Wc();a.wc(c);Wc();--Q.Rc},a.target.addEventListener(a.kc,a.Fd,a.tc),Q.jc.push(a);else for(var b=0;b<Q.jc.length;++b)Q.jc[b].target==a.target&&Q.jc[b].kc==a.kc&&Sc(b--);return 0}function Yc(a){return a==window?"#window":a==screen?"#screen":a?.nodeName??""}
var Q={me:0,Ee:0,hd:0,Xc:0,td:0,qd:0,dd:0,ve:0,Ke:0,ue:0,gd:0,kd:0,sd:0,pd:0,Ne(){for(;Q.jc.length;)Sc(Q.jc.length-1);Q.Ac=[]},Rc:0,Ac:[],jc:[],ge:(a,b)=>{for(var c=0;c<Q.jc.length;++c)Q.jc[c].target!=a||b&&b!=Q.jc[c].kc||Sc(c--)},Oe(a){var b=!1;for(let c=0;c<Q.jc.length;++c){let d=Q.jc[c];d.target===a.target&&d.oc===a.oc&&d.lc===a.lc&&d.uc===a.uc&&(Sc(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Zc=[0,globalThis.document??0,globalThis.window??
0],R=a=>{a=a>2?a?D(t,a):"":a;return Zc[a]||globalThis.document?.querySelector(a)},ad=a=>{var b=Ra(a)+1,c=$c(b);E(a,t,c,b);return c},dd=a=>{var b=bd(),c=$c(8),d=c+4;a=ad(a.id);if(a=R(a))w[c>>2]=a.width,w[d>>2]=a.height;c=[w[c>>2],w[d>>2]];cd(b);return c},ed=(a,b,c)=>{a=R(a);if(!a)return-4;a.width=b;a.height=c;return 0},fd=(a,b,c)=>{if(a.se){var d=bd();a=ad(a.id);ed(a,b,c);cd(d)}else a.width=b,a.height=c},gd={},hd=[],S=a=>{var b=hd[a];b||(hd[a]=b=jd.get(a));return b},ld=a=>{function b(){kd()||(document.removeEventListener("fullscreenchange",
b),document.removeEventListener("webkitfullscreenchange",b),fd(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=k,l||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=l,a.style.paddingLeft=h,a.style.paddingRight=r,a.style.paddingTop=u,a.style.paddingBottom=v,a.style.marginLeft=z,a.style.marginRight=C,a.style.marginTop=I,a.style.marginBottom=H,document.body.style.margin=F,document.documentElement.style.overflow=Z,document.body.scroll=L,a.style.imageRendering=
Zd,a.Mc&&a.Mc.Bc.viewport(0,0,d,e),gd.Qc&&S(gd.Qc)(37,0,gd.wd))}var c=dd(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,k=a.style.backgroundColor,l=document.body.style.backgroundColor,h=a.style.paddingLeft,r=a.style.paddingRight,u=a.style.paddingTop,v=a.style.paddingBottom,z=a.style.marginLeft,C=a.style.marginRight,I=a.style.marginTop,H=a.style.marginBottom,F=document.body.style.margin,Z=document.documentElement.style.overflow,L=document.body.scroll,Zd=a.style.imageRendering;document.addEventListener("fullscreenchange",
b);document.addEventListener("webkitfullscreenchange",b)},md=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},nd=a=>Zc.indexOf(a)<0?a.getBoundingClientRect():{left:0,top:0},Uc=(a,b)=>{if(b.nd!=0||b.ad!=0){ld(a);var c=b.he?innerWidth:screen.width,d=b.he?innerHeight:screen.height,e=nd(a),f=e.width;e=e.height;var g=dd(a),k=g[0];g=g[1];b.nd==3?(md(a,(d-e)/2,(c-f)/2),c=f,d=e):b.nd==2&&(c*g<k*d?(f=g*c/k,md(a,(d-f)/2,0),d=f):(f=k*d/g,md(a,0,(c-f)/
2),c=f));var l;(l=a.style).backgroundColor||(l.backgroundColor="black");let h;(h=document.body.style).backgroundColor||(h.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";b.Vd==1&&(a.style.imageRendering="optimizeSpeed",a.style.imageRendering="-moz-crisp-edges",a.style.imageRendering="-o-crisp-edges",a.style.imageRendering="-webkit-optimize-contrast",a.style.imageRendering="optimize-contrast",a.style.imageRendering="crisp-edges",a.style.imageRendering="pixelated");l=b.ad==2?devicePixelRatio:
1;b.ad!=0&&(c=c*l|0,d=d*l|0,fd(a,c,d),a.Mc&&a.Mc.Bc.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return Q.fullscreenEnabled()?-3:-1;gd=b;b.Qc&&S(b.Qc)(37,0,b.wd);return 0};function kd(){return document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement}
var od=a=>{setTimeout(()=>{Nc(a)},1E4)},pd=!1;
function gb(){function a(){pd=document.pointerLockElement===m.canvas}if(!qd){qd=!0;eb.push({canHandle:c=>!m.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c),handle:async(c,d)=>{var e=new Blob([c],{type:rd(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:rd(d)}));var f=URL.createObjectURL(e);return new Promise((g,k)=>{var l=new Image;l.onload=()=>{var h=document.createElement("canvas");h.width=l.width;h.height=l.height;h.getContext("2d").drawImage(l,0,0);URL.revokeObjectURL(f);
g(c)};l.onerror=()=>{n(`Image ${f} could not be decoded`);k()};l.src=f})}});eb.push({canHandle:c=>!m.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1},handle:async(c,d)=>new Promise(e=>{function f(){g||(g=!0,e(c))}var g=!1,k=new Blob([c],{type:rd(d)});k=URL.createObjectURL(k);var l=new Audio;l.addEventListener("canplaythrough",()=>f(l),!1);l.onerror=()=>{if(!g){n(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);for(var h="data:audio/x-"+d.slice(-3)+";base64,",
r="",u=0,v=0,z=0;z<c.length;z++)for(u=u<<8|c[z],v+=8;v>=6;){var C=u>>v-6&63;v-=6;r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[C]}v==2?(r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&3)<<4],r+="=="):v==4&&(r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&15)<<2],r+="=");l.src=h+r;f(l)}};l.src=k;od(()=>{f(l)})})});var b=m.canvas;b&&(document.addEventListener("pointerlockchange",a,!1),m.elementPointerLock&&b.addEventListener("click",
c=>{!pd&&m.canvas.requestPointerLock&&(m.canvas.requestPointerLock(),c.preventDefault())},!1))}}function rd(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}
var fb={},qd,sd=(a,b)=>{if(!Q.fullscreenEnabled())return-1;a=R(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?(navigator.userActivation?navigator.userActivation.isActive:Q.Rc&&Q.zd.Pc)?Uc(a,b):b.Sd?(Tc([a,b]),1):-2:-3:-4},td=(a,b,c,d,e,f)=>{Q.dd||(Q.dd=T(256));a={target:R(a),kc:f,oc:e,uc:b,lc:d,wc:g=>{var k=g.target.id??"",l=Q.dd;E(Yc(g.target),t,l+0,128);E(k,t,l+128,128);S(d)(e,l,b)&&g.preventDefault()},tc:c};return Xc(a)},ud=(a,b,c,d,e)=>{Q.gd||(Q.gd=T(276));return Xc({target:a,kc:e,
oc:19,uc:b,lc:d,wc:f=>{var g=Q.gd,k=kd(),l=!!k;p[g]=l;p[g+1]=Q.fullscreenEnabled();var h=l?k:Q.fe,r=h?.id??"";E(Yc(h),t,g+2,128);E(r,t,g+130,128);w[g+260>>2]=h?.clientWidth??0;w[g+264>>2]=h?.clientHeight??0;w[g+268>>2]=screen.width;w[g+272>>2]=screen.height;l&&(Q.fe=k);S(d)(19,g,b)&&f.preventDefault()},tc:c})},vd=(a,b,c,d,e,f)=>{Q.hd||(Q.hd=T(160));a={target:R(a),kc:f,oc:e,uc:b,lc:d,wc:g=>{var k=Q.hd;y[k>>3]=g.timeStamp;var l=k>>2;w[l+2]=g.location;p[k+12]=g.ctrlKey;p[k+13]=g.shiftKey;p[k+14]=g.altKey;
p[k+15]=g.metaKey;p[k+16]=g.repeat;w[l+5]=g.charCode;w[l+6]=g.keyCode;w[l+7]=g.which;E(g.key??"",t,k+32,32);E(g.code??"",t,k+64,32);E(g.char??"",t,k+96,32);E(g.locale??"",t,k+128,32);S(d)(e,k,b)&&g.preventDefault()},tc:c};return Xc(a)},wd=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;w[d+2]=b.screenX;w[d+3]=b.screenY;w[d+4]=b.clientX;w[d+5]=b.clientY;p[a+24]=b.ctrlKey;p[a+25]=b.shiftKey;p[a+26]=b.altKey;p[a+27]=b.metaKey;q[d*2+14]=b.button;q[d*2+15]=b.buttons;w[d+8]=b.movementX;w[d+9]=b.movementY;a=nd(c);
w[d+10]=b.clientX-(a.left|0);w[d+11]=b.clientY-(a.top|0)},xd=(a,b,c,d,e,f)=>{Q.Xc||(Q.Xc=T(64));a=R(a);return Xc({target:a,Pc:f!="mousemove"&&f!="mouseenter"&&f!="mouseleave",kc:f,oc:e,uc:b,lc:d,wc:g=>{wd(Q.Xc,g,a);S(d)(e,Q.Xc,b)&&g.preventDefault()},tc:c})},yd=(a,b,c,d)=>{Q.kd||(Q.kd=T(257));return Xc({target:a,kc:"pointerlockchange",oc:20,uc:b,lc:d,wc:e=>{var f=Q.kd,g=document.pointerLockElement;p[f]=!!g;var k=g?.id??"";E(Yc(g),t,f+1,128);E(k,t,f+129,128);S(d)(20,f,b)&&e.preventDefault()},tc:c})},
zd=(a,b,c,d)=>{Q.qd||(Q.qd=T(36));a=R(a);return Xc({target:a,kc:"resize",oc:10,uc:b,lc:d,wc:e=>{if(e.target==a){var f=document.body;if(f){var g=Q.qd;w[g>>2]=0;w[g+4>>2]=f.clientWidth;w[g+8>>2]=f.clientHeight;w[g+12>>2]=innerWidth;w[g+16>>2]=innerHeight;w[g+20>>2]=outerWidth;w[g+24>>2]=outerHeight;w[g+28>>2]=pageXOffset|0;w[g+32>>2]=pageYOffset|0;S(d)(10,g,b)&&e.preventDefault()}}},tc:c})},Ad=(a,b,c,d,e,f)=>{Q.pd||(Q.pd=T(1552));a=R(a);return Xc({target:a,Pc:f=="touchstart"||f=="touchend",kc:f,oc:e,
uc:b,lc:d,wc:g=>{var k={},l=g.touches;for(var h of l)h.Id=h.Md=0,k[h.identifier]=h;for(var r of g.changedTouches)r.Id=1,k[r.identifier]=r;for(var u of g.targetTouches)k[u.identifier].Md=1;l=Q.pd;y[l>>3]=g.timeStamp;p[l+12]=g.ctrlKey;p[l+13]=g.shiftKey;p[l+14]=g.altKey;p[l+15]=g.metaKey;h=l+16;r=nd(a);u=0;for(let v of Object.values(k))if(k=h>>2,w[k]=v.identifier,w[k+1]=v.screenX,w[k+2]=v.screenY,w[k+3]=v.clientX,w[k+4]=v.clientY,w[k+5]=v.pageX,w[k+6]=v.pageY,p[h+28]=v.Id,p[h+29]=v.Md,w[k+8]=v.clientX-
(r.left|0),w[k+9]=v.clientY-(r.top|0),h+=48,++u>31)break;w[l+8>>2]=u;S(d)(e,l,b)&&g.preventDefault()},tc:c})},Bd=(a,b,c)=>{var d=Zc[1];Q.sd||(Q.sd=T(8));return Xc({target:d,kc:"visibilitychange",oc:21,uc:a,lc:c,wc:e=>{var f=Q.sd,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);p[f]=document.hidden;w[f+4>>2]=g;S(c)(21,f,a)&&e.preventDefault()},tc:b})},Cd=(a,b,c,d)=>{Q.td||(Q.td=T(96));return Xc({target:a,Pc:!0,kc:"wheel",oc:9,uc:b,lc:d,wc:e=>{var f=Q.td;wd(f,e,a);y[f+
64>>3]=e.deltaX;y[f+72>>3]=e.deltaY;y[f+80>>3]=e.deltaZ;w[f+88>>2]=e.deltaMode;S(d)(9,f,b)&&e.preventDefault()},tc:c})},U,Dd=a=>{var b="EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return a.getSupportedExtensions()?.filter(c=>b.includes(c))??[]},Ed=1,Fd=[],V=[],Gd=[],Hd=[],Id=[],W=[],Jd=[],Kd=[],Ld=[],Md={},Nd={},Od=4,Pd=0,Qd=a=>{for(var b=Ed++,c=a.length;c<b;c++)a[c]=null;return b},Rd=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=U[c](),g=f&&Qd(d);f?(f.name=g,d[g]=f):X||=1282;w[b+e*4>>2]=g}},Td=(a,b)=>{a.Cc||(a.Cc=a.getContext,a.getContext=function(d,e){e=a.Cc(d,e);return d=="webgl"==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?Sd(c,b):0},Sd=
(a,b)=>{var c=Qd(Kd),d={handle:c,attributes:b,version:b.ce,Bc:a};a.canvas&&(a.canvas.Mc=d);Kd[c]=d;if(typeof b.Ed=="undefined"||b.Ed)if((a=d)||(a=Y),!a.Xd){a.Xd=!0;b=a.Bc;b.Ie=b.getExtension("WEBGL_multi_draw");b.Be=b.getExtension("EXT_polygon_offset_clamp");b.Ae=b.getExtension("EXT_clip_control");b.Qe=b.getExtension("WEBGL_polygon_mode");b.we=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Ge=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");a.version>=2&&
(b.Cd=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(a.version<2||!b.Cd)b.Cd=b.getExtension("EXT_disjoint_timer_query");for(var e of Dd(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}return c},X,Y,Ud=["default","low-power","high-performance"],Vd={},Xd=()=>{if(!Wd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ea},b;for(b in Vd)Vd[b]===void 0?delete a[b]:a[b]=Vd[b];
var c=[];for(b in a)c.push(`${b}=${a[b]}`);Wd=c}return Wd},Wd,Yd=[],$d=()=>{var a=Dd(U);return a=a.concat(a.map(b=>"GL_"+b))},ae=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:c!=0&&c!=1&&(X||=1280);return;case 34814:case 36345:d=0;break;case 34466:var e=U.getParameter(34467);d=e?e.length:0;break;case 33309:if(Y.version<2){X||=1282;return}d=$d().length;break;case 33307:case 33308:if(Y.version<2){X||=1280;return}d=a==33307?3:0}if(d===void 0)switch(e=U.getParameter(a),typeof e){case "number":d=
e;break;case "boolean":d=e?1:0;break;case "string":X||=1280;return;case "object":if(e===null)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:X||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:w[b+a*4>>
2]=e[a];break;case 2:ta[b+a*4>>2]=e[a];break;case 4:p[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){X||=1280;n(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:X||=1280;n(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:c=d;x[b>>2]=c;x[b+4>>2]=(c-x[b>>2])/4294967296;break;case 0:w[b>>2]=d;break;case 2:ta[b>>2]=d;break;case 4:p[b]=d?1:0}}else X||=
1281},be=a=>{var b=Ra(a)+1,c=T(b);c&&E(a,t,c,b);return c},ce=a=>a.slice(-1)=="]"&&a.lastIndexOf("["),de=a=>{a-=5120;return a==0?p:a==1?t:a==2?q:a==4?w:a==6?ta:a==5||a==28922||a==28520||a==30779||a==30782?x:sa},ee=(a,b,c,d,e)=>{a=de(a);b=d*(({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT*(Pd||c)+Od-1&-Od);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))};mb=Array(4096);Bb(J,"/");N("/tmp");N("/home");N("/home/web_user");
(function(){N("/dev");Va(259,{read:()=>0,write:(d,e,f,g)=>g,qc:()=>0});Eb("/dev/null",259);Ua(1280,Xa);Ua(1536,Ya);Eb("/dev/tty",1280);Eb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{b===0&&(Ja(a),b=a.byteLength);return a[--b]};Rb("/dev","random",c);Rb("/dev","urandom",c);N("/dev/shm");N("/dev/shm/tmp")})();
(function(){N("/proc");var a=N("/proc/self");N("/proc/self/fd");Bb({rc(){var b=$a(a,"fd",16895,73);b.bc={qc:J.bc.qc};b.ac={lookup(c,d){c=+d;var e=xb(c);c={parent:null,rc:{Kd:"fake"},ac:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(kb.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();m.requestAnimationFrame=Ac;m.pauseMainLoop=Qc;m.resumeMainLoop=function(){Gc++;var a=tc,b=uc,c=vc;vc=null;Pc(c,0,!1,Hc,!0);Cc(a,b);xc()};
m.preMainLoop&&Mc.push(m.preMainLoop);m.postMainLoop&&Oc.push(m.postMainLoop);for(let a=0;a<32;++a)Yd.push(Array(a));m.noExitRuntime&&(Ha=m.noExitRuntime);m.preloadPlugins&&(eb=m.preloadPlugins);m.print&&(ma=m.print);m.printErr&&(n=m.printErr);m.wasmBinary&&(na=m.wasmBinary);m.arguments&&(da=m.arguments);m.thisProgram&&(ea=m.thisProgram);if(m.preInit)for(typeof m.preInit=="function"&&(m.preInit=[m.preInit]);m.preInit.length>0;)m.preInit.shift()();m.addRunDependency=Ga;m.removeRunDependency=Fa;
m.FS_preloadFile=async(a,b,c,d,e,f,g,k)=>{var l=b?Oa(La(a+"/"+b)):a,h=`cp ${l}`;Ga(h);try{var r=c;typeof c=="string"&&(r=await db(c));r=await hb(r,l);k?.();f||Qb(a,b,r,d,e,g)}finally{Fa(h)}};m.FS_unlink=(...a)=>Hb(...a);m.FS_createPath=(...a)=>Ob(...a);m.FS_createDevice=(...a)=>Rb(...a);m.FS_createDataFile=(...a)=>Qb(...a);m.FS_createLazyFile=(...a)=>Tb(...a);
var fe={139464:(a,b,c)=>{a=a?D(t,a,b):"";console[["debug","info","warn","error"][c]||"log"](a)},139606:()=>window.matchMedia("(dynamic-range: high)").matches?1:0,139674:(a,b)=>{document.title=a?D(t,a,b):""},139717:a=>{var b=Zc["!ZyWindowHTML5"];b&&(b.style.display=a?"block":"none")},139843:()=>{var a=Zc["!ZyWindowHTML5"];a&&a.focus()},139939:()=>window.devicePixelRatio||1,139982:()=>{Zc["!ZyWindowHTML5"]=m.canvas},140040:()=>window.devicePixelRatio||1,140083:()=>window.devicePixelRatio||1},ge,T,$b,
ic,cd,$c,bd,ra,jd,he={ub:function(a,b,c){try{var d=Yb(a),e=d.Ec.accept(d);b&&bc(b,e.family,fc(e.mc),e.nc,c);return e.stream.fd}catch(f){if(typeof O=="undefined"||f.name!=="ErrnoError")throw f;return-f.cc}},tb:function(a,b,c){try{var d=Yb(a),e=kc(b,c);d.Ec.bind(d,e.ec,e.port);return 0}catch(f){if(typeof O=="undefined"||f.name!=="ErrnoError")throw f;return-f.cc}},c:function(a,b,c){lc=c;try{var d=xb(a);switch(b){case 0:var e=mc();if(e<0)break;for(;kb[e];)e++;return zb(d,e).fd;case 1:case 2:return 0;
case 3:return d.flags;case 4:return e=mc(),d.flags=d.flags&-289793|e&289792,0;case 12:return e=mc(),q[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if(typeof O=="undefined"||f.name!=="ErrnoError")throw f;return-f.cc}},Eb:function(a,b){try{if(b===0)return-28;var c=Ra("/")+1;if(b<c)return-68;E("/",t,a,b);return c}catch(d){if(typeof O=="undefined"||d.name!=="ErrnoError")throw d;return-d.cc}},zb:function(a,b,c){try{var d=xb(a);if(!d.Dc){var e=M(d.path,{Nc:!0}).node;var f=wb(e.ac.readdir,54)(e);
d.Dc=f}a=0;var g=Mb(d,0,1),k=Math.floor(g/280),l=Math.min(d.Dc.length,k+Math.floor(c/280));for(c=k;c<l;c++){var h=d.Dc[c];if(h==="."){var r=d.node.id;var u=4}else if(h==="..")r=M(d.path,{parent:!0}).node.id,u=4;else{try{var v=ab(d.node,h)}catch(z){if(z?.cc===28)continue;throw z;}r=v.id;u=(v.mode&61440)===8192?2:K(v.mode)?4:(v.mode&61440)===40960?10:8}A[b+a>>3]=BigInt(r);A[b+a+8>>3]=BigInt((c+1)*280);q[b+a+16>>1]=280;p[b+a+18]=u;E(h,t,b+a+19,256);a+=280}Mb(d,c*280,0);return a}catch(z){if(typeof O==
"undefined"||z.name!=="ErrnoError")throw z;return-z.cc}},Hb:function(a,b,c){lc=c;try{var d=xb(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.xc.Yd){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=mc();w[e>>2]=25856;w[e+4>>2]=5;w[e+8>>2]=191;w[e+12>>2]=35387;for(var f=0;f<32;f++)p[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.xc.Zd)for(e=
mc(),a=[],f=0;f<32;f++)a.push(p[e+f+17]);return 0;case 21519:if(!d.tty)return-59;e=mc();return w[e>>2]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:e=mc();if(!d.bc.Sc)throw new G(59);return d.bc.Sc(d,b,e);case 21523:if(!d.tty)return-59;d.tty.xc.$d&&(f=[24,80],e=mc(),q[e>>1]=f[0],q[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if(typeof O=="undefined"||g.name!=="ErrnoError")throw g;return-g.cc}},sb:function(a,b){try{var c=
Yb(a);c.Ec.listen(c,b);return 0}catch(d){if(typeof O=="undefined"||d.name!=="ErrnoError")throw d;return-d.cc}},Cb:function(a,b,c){try{return b=b?D(t,b):"",b=nc(a,b),N(b,c&-19),0}catch(d){if(typeof O=="undefined"||d.name!=="ErrnoError")throw d;return-d.cc}},Fb:function(a,b,c,d){try{b=b?D(t,b):"";var e=d&256;b=nc(a,b,d&4096);return oc(c,e?Ib(b,!0):Ib(b))}catch(f){if(typeof O=="undefined"||f.name!=="ErrnoError")throw f;return-f.cc}},P:function(a,b,c,d){lc=d;try{b=b?D(t,b):"";b=nc(a,b);var e=d?mc():0;
c&64&&(e&=-19);return Kb(b,c,e).fd}catch(f){if(typeof O=="undefined"||f.name!=="ErrnoError")throw f;return-f.cc}},rb:function(a,b,c,d,e,f){try{var g=Yb(a),k=Ub(g,c);if(!k)return 0;e&&bc(e,g.family,fc(k.ec),k.port,f);t.set(k.buffer,b);return k.buffer.byteLength}catch(l){if(typeof O=="undefined"||l.name!=="ErrnoError")throw l;return-l.cc}},xb:function(a){try{return a=a?D(t,a):"",Gb(a),0}catch(b){if(typeof O=="undefined"||b.name!=="ErrnoError")throw b;return-b.cc}},qb:function(a,b,c,d,e,f){try{var g=
Yb(a);if(!e)return Nb(g.stream,p,b,c);var k=kc(e,f);return Vb(g,p,b,c,k.ec,k.port)}catch(l){if(typeof O=="undefined"||l.name!=="ErrnoError")throw l;return-l.cc}},pb:function(a,b,c){try{return P.createSocket(a,b,c).stream.fd}catch(d){if(typeof O=="undefined"||d.name!=="ErrnoError")throw d;return-d.cc}},Gb:function(a,b){try{return a=a?D(t,a):"",oc(b,Ib(a))}catch(c){if(typeof O=="undefined"||c.name!=="ErrnoError")throw c;return-c.cc}},yb:function(a,b,c){try{b=b?D(t,b):"";b=nc(a,b);if(c)if(c===512)Gb(b);
else return-28;else Hb(b);return 0}catch(d){if(typeof O=="undefined"||d.name!=="ErrnoError")throw d;return-d.cc}},Nb:()=>B(""),Ab:function(a,b){a=a<-9007199254740992||a>9007199254740992?NaN:Number(a);a=new Date(a*1E3);w[b>>2]=a.getSeconds();w[b+4>>2]=a.getMinutes();w[b+8>>2]=a.getHours();w[b+12>>2]=a.getDate();w[b+16>>2]=a.getMonth();w[b+20>>2]=a.getFullYear()-1900;w[b+24>>2]=a.getDay();var c=a.getFullYear();w[b+28>>2]=(c%4!==0||c%100===0&&c%400!==0?qc:pc)[a.getMonth()]+a.getDate()-1|0;w[b+36>>2]=
-(a.getTimezoneOffset()*60);c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();w[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},Bb:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();x[a>>2]=Math.max(f,e)*60;w[b>>2]=Number(f!=e);b=g=>{var k=Math.abs(g);return`UTC${g>=0?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(f);
b=b(e);e<f?(E(a,t,c,17),E(b,t,d,17)):(E(a,t,d,17),E(b,t,c,17))},Mb:function(a,b,c){if(!(a>=0&&a<=3))return 28;A[c>>3]=BigInt(Math.round((a===0?Date.now():performance.now())*1E3*1E3));return 0},v:(a,b,c)=>{b=sc(b,c);return fe[a](...b)},g:(a,b,c)=>{b=sc(b,c);return fe[a](...b)},ma:()=>{Qc();vc=null},Lb:()=>Date.now(),S:()=>{if(!Q.fullscreenEnabled())return-1;Vc();var a=Zc[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();
else return-1;return 0},ka:()=>globalThis.devicePixelRatio??1,Ob:(a,b,c)=>{a=R(a);if(!a)return-4;a=nd(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},wb:()=>536870912,f:()=>performance.now(),la:(a,b)=>{w[a>>2]=screen.width;w[b>>2]=screen.height},T:(a,b,c)=>sd(a,{nd:w[c>>2],ad:w[c+4>>2],Vd:w[c+8>>2],Sd:b,Qc:w[c+12>>2],wd:w[c+16>>2]}),vb:a=>{var b=t.length;a>>>=0;if(a>536870912)return!1;for(var c=1;c<=4;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(536870912,Math.ceil(Math.max(a,d)/
65536)*65536)-ra.buffer.byteLength+65535)/65536|0;try{ra.grow(d);qa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},Y:(a,b,c,d)=>td(a,b,c,d,12,"blur"),R:ed,Pb:(a,b,c)=>{a=R(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},Z:(a,b,c,d)=>td(a,b,c,d,13,"focus"),W:(a,b,c,d)=>{if(!Q.fullscreenEnabled())return-1;a=R(a);if(!a)return-4;ud(a,b,c,d,"webkitfullscreenchange");return ud(a,b,c,d,"fullscreenchange")},ha:(a,b,c,d)=>vd(a,b,c,d,2,"keydown"),ga:(a,b,c,d)=>vd(a,b,c,
d,3,"keyup"),na:(a,b,c,d)=>{Pc(()=>S(a)(b),c,d,b)},ea:(a,b,c,d)=>xd(a,b,c,d,5,"mousedown"),fa:(a,b,c,d)=>xd(a,b,c,d,8,"mousemove"),da:(a,b,c,d)=>xd(a,b,c,d,6,"mouseup"),V:(a,b,c,d)=>document.body?.requestPointerLock?(a=R(a))?yd(a,b,c,d):-4:-1,X:(a,b,c,d)=>zd(a,b,c,d),_:(a,b,c,d)=>Ad(a,b,c,d,25,"touchcancel"),aa:(a,b,c,d)=>Ad(a,b,c,d,23,"touchend"),$:(a,b,c,d)=>Ad(a,b,c,d,24,"touchmove"),ba:(a,b,c,d)=>Ad(a,b,c,d,22,"touchstart"),U:(a,b,c)=>Zc[1]?Bd(a,b,c):-4,ca:(a,b,c,d)=>(a=R(a))?typeof a.onwheel!=
"undefined"?Cd(a,b,c,d):-1:-4,ra:(a,b)=>{var c=b>>2;b={alpha:!!p[b+0],depth:!!p[b+1],stencil:!!p[b+2],antialias:!!p[b+3],premultipliedAlpha:!!p[b+4],preserveDrawingBuffer:!!p[b+5],powerPreference:Ud[w[c+2]],failIfMajorPerformanceCaveat:!!p[b+12],ce:w[c+4],He:w[c+5],Ed:p[b+24],Ud:p[b+25],Le:w[c+7],Pe:p[b+32]};a=R(a);return!a||b.Ud?0:Td(a,b)},w:a=>{Y==a&&(Y=0);Y===Kd[a]&&(Y=null);typeof Q=="object"&&Q.ge(Kd[a].Bc.canvas);Kd[a]?.Bc.canvas&&(Kd[a].Bc.canvas.Mc=void 0);Kd[a]=null},z:a=>{Y=Kd[a];m.ctx=
U=Y?.Bc;return!a||U?0:-5},Jb:(a,b)=>{var c=0,d=0,e;for(e of Xd()){var f=b+c;x[a+d>>2]=f;c+=E(e,t,f,Infinity)+1;d+=4}return 0},Kb:(a,b)=>{var c=Xd();x[a>>2]=c.length;a=0;for(var d of c)a+=Ra(d)+1;x[b>>2]=a;return 0},n:function(a){try{var b=xb(a);Lb(b);return 0}catch(c){if(typeof O=="undefined"||c.name!=="ErrnoError")throw c;return c.cc}},O:function(a,b,c,d){try{a:{var e=xb(a);a=b;for(var f,g=b=0;g<c;g++){var k=x[a>>2],l=x[a+4>>2];a+=8;var h=e,r=k,u=l,v=f,z=p;if(u<0||v<0)throw new G(28);if(h.fd===null)throw new G(8);
if((h.flags&2097155)===1)throw new G(8);if(K(h.node.mode))throw new G(31);if(!h.bc.read)throw new G(28);var C=typeof v!="undefined";if(!C)v=h.position;else if(!h.seekable)throw new G(70);var I=h.bc.read(h,z,r,u,v);C||(h.position+=I);var H=I;if(H<0){var F=-1;break a}b+=H;if(H<l)break;typeof f!="undefined"&&(f+=H)}F=b}x[d>>2]=F;return 0}catch(Z){if(typeof O=="undefined"||Z.name!=="ErrnoError")throw Z;return Z.cc}},Db:function(a,b,c,d){b=b<-9007199254740992||b>9007199254740992?NaN:Number(b);try{if(isNaN(b))return 22;
var e=xb(a);Mb(e,b,c);A[d>>3]=BigInt(e.position);e.Dc&&b===0&&c===0&&(e.Dc=null);return 0}catch(f){if(typeof O=="undefined"||f.name!=="ErrnoError")throw f;return f.cc}},u:function(a,b,c,d){try{a:{var e=xb(a);a=b;for(var f,g=b=0;g<c;g++){var k=x[a>>2],l=x[a+4>>2];a+=8;var h=Nb(e,p,k,l,f);if(h<0){var r=-1;break a}b+=h;if(h<l)break;typeof f!="undefined"&&(f+=h)}r=b}x[d>>2]=r;return 0}catch(u){if(typeof O=="undefined"||u.name!=="ErrnoError")throw u;return u.cc}},Q:(a,b,c,d,e,f,g)=>{b=jc(a,b);if(b.cc)return-6;
a=b.port;var k=b.ec;b=!1;if(c&&d){var l;if(g&1||!(l=ec[k]?ec[k]:null)){if(g&8)return-2}else k=l;c=E(k,t,c,d);c+1>=d&&(b=!0)}e&&f&&(c=E(""+a,t,e,f),c+1>=f&&(b=!0));return b?-12:0},ua:a=>U.activeTexture(a),K:(a,b)=>{U.attachShader(V[a],W[b])},k:(a,b)=>{a==35051?U.Ad=b:a==35052&&(U.Fc=b);U.bindBuffer(a,Fd[b])},o:(a,b,c)=>{U.bindBufferBase(a,b,Fd[c])},p:(a,b,c,d,e)=>{U.bindBufferRange(a,b,Fd[c],d,e)},i:(a,b)=>{U.bindFramebuffer(a,Gd[b])},G:(a,b)=>{U.bindRenderbuffer(a,Hd[b])},ta:(a,b)=>{U.bindSampler(a,
Ld[b])},s:(a,b)=>{U.bindTexture(a,Id[b])},Qb:a=>{U.bindVertexArray(Jd[a])},Da:(a,b)=>U.blendEquationSeparate(a,b),Ea:(a,b,c,d)=>U.blendFuncSeparate(a,b,c,d),E:(a,b,c,d,e,f,g,k,l,h)=>U.blitFramebuffer(a,b,c,d,e,f,g,k,l,h),lb:(a,b,c,d)=>{c&&b?U.bufferData(a,t,d,c,b):U.bufferData(a,b,d)},kb:(a,b,c,d)=>{var e=t;c&&U.bufferSubData(a,b,e,d,c)},La:(a,b,c,d)=>U.clearBufferfi(a,b,c,d),A:(a,b,c)=>{U.clearBufferfv(a,b,ta,c>>2)},Ka:(a,b,c)=>{U.clearBufferiv(a,b,w,c>>2)},D:(a,b,c,d)=>{U.colorMask(!!a,!!b,!!c,
!!d)},db:a=>{U.compileShader(W[a])},Ta:(a,b,c,d,e,f,g,k)=>{U.Fc||!g?U.compressedTexImage2D(a,b,c,d,e,f,g,k):U.compressedTexImage2D(a,b,c,d,e,f,t,k,g)},Qa:(a,b,c,d,e,f,g,k,l)=>{U.Fc||!k?U.compressedTexSubImage2D(a,b,c,d,e,f,g,k,l):U.compressedTexSubImage2D(a,b,c,d,e,f,g,t,l,k)},jb:(a,b,c,d,e)=>U.copyBufferSubData(a,b,c,d,e),ib:()=>{var a=Qd(V),b=U.createProgram();b.name=a;b.Vc=b.Tc=b.Uc=0;b.rd=1;V[a]=b;return a},fb:a=>{var b=Qd(W);W[b]=U.createShader(a);return b},Aa:a=>U.cullFace(a),ja:(a,b)=>{for(var c=
0;c<a;c++){var d=w[b+c*4>>2],e=Fd[d];e&&(U.deleteBuffer(e),e.name=0,Fd[d]=null,d==U.Ad&&(U.Ad=0),d==U.Fc&&(U.Fc=0))}},j:(a,b)=>{for(var c=0;c<a;++c){var d=w[b+c*4>>2],e=Gd[d];e&&(U.deleteFramebuffer(e),e.name=0,Gd[d]=null)}},t:a=>{if(a){var b=V[a];b?(U.deleteProgram(b),b.name=0,V[a]=null):X||=1281}},ia:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+c*4>>2],e=Hd[d];e&&(U.deleteRenderbuffer(e),e.name=0,Hd[d]=null)}},Ua:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+c*4>>2],e=Ld[d];e&&(U.deleteSampler(e),e.name=0,Ld[d]=
null)}},l:a=>{if(a){var b=W[a];b?(U.deleteShader(b),W[a]=null):X||=1281}},N:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+c*4>>2],e=Id[d];e&&(U.deleteTexture(e),e.name=0,Id[d]=null)}},Ma:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+c*4>>2];U.deleteVertexArray(Jd[d]);Jd[d]=null}},Ca:a=>U.depthFunc(a),C:a=>{U.depthMask(!!a)},Na:(a,b)=>U.depthRange(a,b),J:(a,b)=>{U.detachShader(V[a],W[b])},e:a=>U.disable(a),va:a=>{U.disableVertexAttribArray(a)},Fa:(a,b,c)=>{U.drawArrays(a,b,c)},Ga:(a,b,c,d)=>{U.drawArraysInstanced(a,
b,c,d)},L:(a,b)=>{for(var c=Yd[a],d=0;d<a;d++)c[d]=w[b+d*4>>2];U.drawBuffers(c)},Ha:(a,b,c,d)=>{U.drawElements(a,b,c,d)},Ia:(a,b,c,d,e)=>{U.drawElementsInstanced(a,b,c,d,e)},h:a=>U.enable(a),za:a=>{U.enableVertexAttribArray(a)},M:(a,b,c,d)=>{U.framebufferRenderbuffer(a,b,c,Hd[d])},m:(a,b,c,d,e)=>{U.framebufferTexture2D(a,b,c,Id[d],e)},Ib:a=>U.frontFace(a),mb:(a,b)=>{Rd(a,b,"createBuffer",Fd)},q:(a,b)=>{Rd(a,b,"createFramebuffer",Gd)},Xa:(a,b)=>{Rd(a,b,"createRenderbuffer",Hd)},qa:(a,b)=>{Rd(a,b,"createSampler",
Ld)},Va:(a,b)=>{Rd(a,b,"createTexture",Id)},Rb:(a,b)=>{Rd(a,b,"createVertexArray",Jd)},Ra:a=>U.generateMipmap(a),_a:(a,b,c,d,e,f,g)=>{a=V[a];if(b=U.getActiveUniform(a,b))c=g&&E(b.name,t,g,c),d&&(w[d>>2]=c),e&&(w[e>>2]=b.size),f&&(w[f>>2]=b.type)},ob:(a,b)=>ae(a,b,2),a:(a,b)=>ae(a,b,0),gb:(a,b,c,d)=>{a=U.getProgramInfoLog(V[a]);a===null&&(a="(unknown error)");b=b>0&&d?E(a,t,d,b):0;c&&(w[c>>2]=b)},I:(a,b,c)=>{if(c)if(a>=Ed)X||=1281;else if(a=V[a],b==35716)a=U.getProgramInfoLog(a),a===null&&(a="(unknown error)"),
w[c>>2]=a.length+1;else if(b==35719){if(!a.Vc){var d=U.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Vc=Math.max(a.Vc,U.getActiveUniform(a,b).name.length+1)}w[c>>2]=a.Vc}else if(b==35722){if(!a.Tc)for(d=U.getProgramParameter(a,35721),b=0;b<d;++b)a.Tc=Math.max(a.Tc,U.getActiveAttrib(a,b).name.length+1);w[c>>2]=a.Tc}else if(b==35381){if(!a.Uc)for(d=U.getProgramParameter(a,35382),b=0;b<d;++b)a.Uc=Math.max(a.Uc,U.getActiveUniformBlockName(a,b).length+1);w[c>>2]=a.Uc}else w[c>>2]=U.getProgramParameter(a,
b);else X||=1281},bb:(a,b,c,d)=>{a=U.getShaderInfoLog(W[a]);a===null&&(a="(unknown error)");b=b>0&&d?E(a,t,d,b):0;c&&(w[c>>2]=b)},cb:(a,b,c)=>{c?b==35716?(a=U.getShaderInfoLog(W[a]),a===null&&(a="(unknown error)"),w[c>>2]=a?a.length+1:0):b==35720?(a=U.getShaderSource(W[a]),w[c>>2]=a?a.length+1:0):w[c>>2]=U.getShaderParameter(W[a],b):X||=1281},nb:a=>{var b=Md[a];if(!b){switch(a){case 7939:b=be($d().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=U.getParameter(a))||(X||=1280);b=b?be(b):
0;break;case 7938:b=be(`OpenGL ES 3.0 (${U.getParameter(7938)})`);break;case 35724:b=U.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);c!==null&&(c[1].length==3&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=be(b);break;default:X||=1280}Md[a]=b}return b},b:(a,b)=>{if(Y.version<2)return X||=1282,0;var c=Nd[a];if(c)return b<0||b>=c.length?(X||=1281,0):c[b];switch(a){case 7939:return c=$d().map(be),c=Nd[a]=c,b<0||b>=c.length?(X||=1281,0):c[b];default:return X||=
1280,0}},ab:(a,b)=>U.getUniformBlockIndex(V[a],b?D(t,b):""),Za:(a,b)=>{b=b?D(t,b):"";if(a=V[a]){var c=a,d=c.Oc,e=c.Qd,f;if(!d){c.Oc=d={};c.Pd={};var g=U.getProgramParameter(c,35718);for(f=0;f<g;++f){var k=U.getActiveUniform(c,f);var l=k.name;k=k.size;var h=ce(l);h=h>0?l.slice(0,h):l;var r=c.rd;c.rd+=k;e[h]=[k,r];for(l=0;l<k;++l)d[r]=l,c.Pd[r++]=h}}c=a.Oc;d=0;f=b;e=ce(b);e>0&&(d=b.slice(e+1),d=parseInt(d)>>>0,f=b.slice(0,e));if((e=a.Qd[f])&&d<e[0]&&(d+=e[1],c[d]=c[d]||U.getUniformLocation(a,b)))return d}else X||=
1281;return-1},hb:a=>{a=V[a];U.linkProgram(a);a.Oc=0;a.Qd={}},r:(a,b)=>{a==3317?Od=b:a==3314&&(Pd=b);U.pixelStorei(a,b)},Ba:(a,b)=>U.polygonOffset(a,b),sa:a=>U.readBuffer(a),Wa:(a,b,c,d,e)=>U.renderbufferStorageMultisample(a,b,c,d,e),oa:(a,b,c)=>{U.samplerParameterf(Ld[a],b,c)},pa:(a,b,c)=>{U.samplerParameterf(Ld[a],b,ta[c>>2])},d:(a,b,c)=>{U.samplerParameteri(Ld[a],b,c)},Ja:(a,b,c,d)=>U.scissor(a,b,c,d),eb:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=x[c+f*4>>2])?D(t,g,d?x[d+f*4>>2]:void 0):"";
e+=g}U.shaderSource(W[a],e)},y:(a,b,c,d)=>U.stencilFuncSeparate(a,b,c,d),B:a=>U.stencilMask(a),x:(a,b,c,d)=>U.stencilOpSeparate(a,b,c,d),Sa:(a,b,c,d,e,f,g,k,l)=>{if(U.Fc)U.texImage2D(a,b,c,d,e,f,g,k,l);else if(l){var h=de(k);l>>>=31-Math.clz32(h.BYTES_PER_ELEMENT);U.texImage2D(a,b,c,d,e,f,g,k,h,l)}else h=l?ee(k,g,d,e,l):null,U.texImage2D(a,b,c,d,e,f,g,k,h)},F:(a,b,c)=>U.texParameteri(a,b,c),Pa:(a,b,c,d,e,f,g,k,l)=>{if(U.Fc)U.texSubImage2D(a,b,c,d,e,f,g,k,l);else if(l){var h=de(k);U.texSubImage2D(a,
b,c,d,e,f,g,k,h,l>>>31-Math.clz32(h.BYTES_PER_ELEMENT))}else l=l?ee(k,g,e,f,l):null,U.texSubImage2D(a,b,c,d,e,f,g,k,l)},Ya:(a,b)=>{var c=U,d=c.uniform1i;var e=U.Rd;if(e){var f=e.Oc[a];typeof f=="number"&&(e.Oc[a]=f=U.getUniformLocation(e,e.Pd[a]+(f>0?`[${f}]`:"")));a=f}else X||=1282,a=void 0;d.call(c,a,b)},$a:(a,b,c)=>{a=V[a];U.uniformBlockBinding(a,b,c)},H:a=>{a=V[a];U.useProgram(a);U.Rd=a},ya:(a,b)=>{U.vertexAttribDivisor(a,b)},xa:(a,b,c,d,e)=>{U.vertexAttribIPointer(a,b,c,d,e)},wa:(a,b,c,d,e,f)=>
{U.vertexAttribPointer(a,b,c,!!d,e,f)},Oa:(a,b,c,d)=>U.viewport(a,b,c,d)};function ie(a=[]){var b=ge;a.unshift(ea);var c=a.length,d=$c((c+1)*4),e=d,f;for(f of a)x[e>>2]=ad(f),e+=4;x[e>>2]=0;try{var g=b(c,d);pa=g;Dc(g)}catch(k){Ec(k)}}
function je(a=da){function b(){m.calledRun=!0;if(!oa){P.root=Bb(P,null);if(!m.noFSInit&&!nb){var c,d;nb=!0;c??=m.stdin;d??=m.stdout;e??=m.stderr;c?Rb("/dev","stdin",c):Fb("/dev/tty","/dev/stdin");d?Rb("/dev","stdout",null,d):Fb("/dev/tty","/dev/stdout");e?Rb("/dev","stderr",null,e):Fb("/dev/tty1","/dev/stderr");Kb("/dev/stdin",0);Kb("/dev/stdout",1);Kb("/dev/stderr",1)}ke.Tb();ob=!1;m.onRuntimeInitialized?.();m.noInitialRun||ie(a);if(m.postRun)for(typeof m.postRun=="function"&&(m.postRun=[m.postRun]);m.postRun.length;){var e=
m.postRun.shift();Aa.push(e)}za(Aa)}}if(Da>0)Ea=je;else{if(m.preRun)for(typeof m.preRun=="function"&&(m.preRun=[m.preRun]);m.preRun.length;)Ca();za(Ba);Da>0?Ea=je:m.setStatus?(m.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>m.setStatus(""),1);b()},1)):b()}}var ke;
(async function(){function a(c){c=ke=c.exports;ge=m._main=c.Vb;T=c.Wb;$b=c.Xb;ic=c.Yb;cd=c.Zb;$c=c._b;bd=c.$b;ra=c.Sb;jd=c.Ub;qa();Fa("wasm-instantiate");return ke}Ga("wasm-instantiate");var b={a:he};if(m.instantiateWasm)return new Promise(c=>{m.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ua??=m.locateFile?m.locateFile("Tileon_Editor.wasm",ia):ia+"Tileon_Editor.wasm";return function(c){return a(c.instance)}(await xa(b))})();je();
